@startuml vista-estatica

class GestorRegRRes{
    -listaEventosSismicos :EventoSismico
    -listaESNoRevisados
    -eventoSismicoSeleccionado :EventoSismico
    -estadoRechazado :Estado
    -estadoConfirmado :Estado
    -listaDatosSeriesTemporales :NO SE SABE
    -sesion :Sesion
    -empleadoLogueado :Empleado
    -listaEstados :Estado
    -estadoBloqueadoEnRevision :Estado
    -fechaHoraActual
    -pantalla :PanRegRRes
    -nombreAlcance
    -nombreOrigenGeneracion
    -nombreClasificacion
    -ultimoCambioDeEstado :CambioEstado
    -sismografos :Sismografo
    -seleccion

    +nuevaRevisionES()
    +buscarESNoRevisados()
    +ordenarEventosSismicosPorFechaYHora()
    +tomarSeleccionES()
    +buscarEstadoBloqueadoEnRev()
    +bloquearEventoSismico()
    +tomarFechaHoraActual()
    +buscarEmpleadoLogueado()
    +buscarDatosEventoSismico()
    +buscarDatosSeriesTemporales()
    +llamarCUGenerarSismograma()
    +tomarSeleccionResultado()
    +validarDatosMinimos()
    +buscarEstadoRechazado()
    +rechazarEventoSismico()
    +finCU()
}

class PanRegRRes{
    -gestor :GestorRegRRes
    -opcRegRRevision
    -eventosComboBox
    -origentxt
    -Alcancetxt
    -clasificaciontxt
    -seleccionarButton
    -AlcanceLabel
    -ClasificacionLabel
    -OrigenDeGeneracionLabel
    -rechazarButton
    -confirmarButton
    -delegarAExpertoButton
    -verMapaButton
    -modificarDatosButton
    -seleccioneResultadoLabel
    -panelPrincipal

    +opcRegResultadoES()
    +abrirPantalla()
    +mostrarESParaSeleccion()
    +tomarSeleccionES()
    +mostrarDatosEventoSismico()
    +habilitarOpcVerMapa()
    +habilitarOpcModificarDatosES()
    +pedirSeleccionResultadoEvento()
    +tomarSeleccionResultado()
}

class AlcanceSismo{
    -descripcion
    -nombre

    +getNombre()
}

class CambioEstado{
    -fechaHoraFin
    -fechaHoraInicio
    -estado :Estado
    -empleadoResponsable: Empleado

    +esActual()
    +setFechaHoraFin()
    +new()
}

class ClasificacionSismo{
    -kmProfundidadDesde
    -kmProfundidadHasta
    -nombre

    +getNombre()
}

class DetalleMuestraSismica{
    -valor
    -tipoDeDato :TipoDeDato

    +getDatos()
}

class Empleado{
    -apellido
    -mail
    -nombre
    -telefono
}

class EstacionSismologica{
    -codigoEstacion
    -documentacionCertificacionAdq
    -fechaSolicitudCertificacion
    -latitud
    -longitud
    -nombre
    -nroCertificacionAdquisicion
    
    +getCodigoEstacion()
}

class Estado{
    -ambito
    -nombreEstado

    +esAutoDetectado()
    +esPendienteDeRevision()
    +esAmbitoEventoSismico()
    +esBloqueadoEnRevision()
    +esRechazado()
}

class EventoSismico{
    -fechaHoraFin
    -fechaHoraOcurrencia
    -latitudEpicentro
    -latitudHipocentro
    -longitudEpicentro
    -longitudHipocentro
    -valorMagnitud
    -estadoActual :Estado
    -cambioEstado :CambioEstado
    -clasificacion :ClasificacionSismo
    -origenGeneracion :OrigenDeGeneracion
    -alcanceSismo :AlcanceSismo
    -seriesTemporales :SerieTemporal

    +esAutoDetectado()
    +esPendienteDeRevision()
    +getDatosPrincipales()
    +getFechaHoraOcurrencia()
    +getLatitudEpicentro()
    +getLatitudHipocentro()
    +getLongitudEpicentro()
    +getLongitudHipocentro()
    +getValorMagnitud()
    +revisar()
    +buscarUltimoEstado()
    +crearCambioEstado()
    +setEstadoActual()
    +mostrarAlcance()
    +mostrarClasificacion()
    +mostrarOrigenGeneracion()
    +buscarDatosSeriesTemporales()
    +clasificarDatosPorEstacionSismologica()
    +rechazar()
    +actualizarUltimoEstado()
}

class MuestraSismica{
    -fechaHoraMuestra
    -detalleMuestraSismica :DetalleMuestraSismica

    +getDatos()
}

class OrigenDeGeneracion{
    -nombre
    -descripcion

    +getNombre()
}

class SerieTemporal{
    -condicionAlarma
    -fechaHoraInicioRegistroMuestras
    -fechaHoraRegistro
    -frecuenciaMuestreo
    -estado :Estado
    -muestrasSismicas :MuestraSismica

    +getDatos()
    +obtenerEstacionSismologica()
}

class Sesion{
    -fechaHoraInicio
    -fechaHoraCierre
    -usuario

    +obtenerEmpleadoLogueado()
}

class Sismografo{
    -fechaAdquisicion
    -identificadorSismografo
    -nroSerie
    -seriesTemporales :SerieTemporal
    -estacionSismologica :EstacionSismologica
    -estadoActual :Estado
    -cambiosDeEstado :CambioEstado

    +esSismografoDeSerieTemporal()
    +getCodigoEstacion()
}

class TipoDeDato{
    -denominacion
    -nombreUnidadMedida
    -valorUmbral

    +getDenominacion()
}

class Usuario{
    -contrasenia
    -nombreUsuario
    -empleado :Empleado

    +getEmpleado()
}

PanRegRRes ..> GestorRegRRes

GestorRegRRes ..> PanRegRRes

GestorRegRRes ..> EventoSismico

GestorRegRRes ..> Estado

GestorRegRRes ..> Sesion

EventoSismico -->"1" Estado

Sesion -->"1" Usuario

Usuario -->"1" Empleado

CambioEstado -->"1" Estado

CambioEstado -->"1" Empleado

EventoSismico -->"1" AlcanceSismo

EventoSismico -->"1" ClasificacionSismo

EventoSismico -->"1" OrigenDeGeneracion

EventoSismico -->"0..*" SerieTemporal

EventoSismico -->"0..*"CambioEstado

SerieTemporal -->"0..*" MuestraSismica

SerieTemporal -->"1"Estado

MuestraSismica -->"0..*" DetalleMuestraSismica

Sismografo -->"1" Estado

Sismografo -->"0..*" CambioEstado

DetalleMuestraSismica -->"1" TipoDeDato

Sismografo -->"0..*" SerieTemporal

Sismografo -->"1" EstacionSismologica
@enduml